- name: "Create User {{item.username}}"
  tags: [test]
  become: true
  ansible.builtin.user:
    name: '{{ item["username"] }}'
    create_home: yes
    shell: /bin/bash
    append: yes
    groups: '{{item.groups | default([]) | join(",")}}'
    password: '{{item.password | default("!")}}'
    expires: '{{(item.expires | to_datetime).strftime("%s")}}'
    update_password: 'on_create'
- name: Deploy keys
  tags: [test]
  become: true
  ansible.posix.authorized_key:
    user: "{{ item.username }}"
    state: present
    key: '{{ keys }}'
  loop: "{{item.authorized_keys}}"
  when: item.authorized_keys is defined
  loop_control:
    loop_var: keys
- name: sudo allow
  tags: [test]
  become: true
  community.general.sudoers:
    runas: root
    state: present
    user: '{{ item.username }}'
    commands: '{{ item.sudo_allow }}'
    name: "ansible_sudoers_{{item[0].username | replace('.', '_')}}"
  when: item.sudo_allow is defined
- name: sudo deny
  tags: [test]
  become: true
  community.general.sudoers:
    state: absent
    name: "ansible_sudoers_{{item[0].username | replace('.', '_')}}"
  when: item.sudo_allow is not defined
  