- name: "Create User {{item.username}}"
  tag: [test]
  become: true
  ansible.builtin.user:
    name: '{{ item["username"] }}'
    create_home: yes
    shell: /bin/bash
    append: yes
    groups: '{{item.groups | default([]) | join(",")}}'
    password: '{{item.password | default("!")}}'
    expires: '{{(item.expires | to_datetime).strftime("%s")}}'
    update_password: 'on_create'
- name: Deploy keys
  tag: [test]
  become: true
  ansible.posix.authorized_key:
    user: "{{ item[0].username }}"
    state: present
    key: '{{ item[1] }}'
  loop: "{{item.authorized_keys}}"
  when: item.authorized_keys is defined
- name: sudo allow
  tag: [test]
  become: true
  community.general.sudoers:
    runas: root
    state: present
    user: '{{ item[0].username }}'
    commands: '{{ item[1] }}'
    name: "ansible_sudoers_{{item[0].username | replace('.', '_')}}"
  loop: "{{item.sudo_allow}}"
  when: item.sudo_allow is defined
- name: sudo deny
  tag: [test]
  become: true
  community.general.sudoers:
    runas: root
    state: absent
    user: '{{ item[0].username }}'
    commands: '{{ item[1] }}'
    name: "ansible_sudoers_{{item[0].username | replace('.', '_')}}"
  loop: "{{item.sudo_deny}}"
  when: item.sudo_deny is defined
  