- name: Create Users
  become: true
  ansible.builtin.user:
    name: '{{ item["username"] }}'
    create_home: yes
    shell: /bin/bash
    append: yes
    groups: '{{item.groups | default([]) | join(",")}}'
    password: '{{item.password | default("!")}}'
    expires: '{{(item.expires | to_datetime).strftime("%s")}}'
    update_password: 'on_create'
  loop: "{{users}}"
- name: Deploy keys
  become: true
  ansible.posix.authorized_key:
    user: "{{ item.username }}"
    state: present
    key: '{{ item[1] }}'
  loop: "{{users|subelements('authorized_keys')}}"