- name: Create Users
  become: true
  ansible.builtin.user:
    name: '{{ item["username"] }}'
    create_home: yes
    shell: /bin/bash
    append: yes
    groups: '{{item.groups | default([]) | join(",")}}'
    password: '!'
    expires: '{{(item.expires | to_datetime).strftime("%s")}}'
  loop: "{{users}}"
- name: Deploy keys
  become: true
  ansible.posix.authorized_key:
    user: "{{ item.username }}"
    state: present
    key: '{{ item.authorized_keys | join("\n") }}'
  loop: "{{users}}"