- name: Create btrfs subvolume for Docker Volumes
  become: true
  community.general.btrfs_subvolume:
    name: /var/lib/docker/volumes
    recursive: true
    state: present

- name: Add Docker GPG APT key
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
- name: Add Docker Repository
  become: true
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu jammy stable
    state: present
- name: Add docker-components
  become: true
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: latest
    update_cache: true

# The following updates the Docker Daemon File to fully take advantage of CUDA.
- name: Install Docker config
  become: true
  notify: Restart Docker
  ansible.builtin.copy:
    src: docker/daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: '0622' # user read/write, group read