- name: Deploy label_studio password
  tags: [test]
  ansible.builtin.script:
    cmd: scripts/deploy_label_studio_pass.sh
    creates: "{{ansible_env.HOME}}/waiter/.secrets/label_studio_admin_password.env"
    executable: /bin/bash
- name: Ensure label studio admin group exists
  tags: [test]
  become: true
  ansible.builtin.group:
    name: label_studio_admin

- name: Ensure label studio files dir exists
  tags: [test]
  become: true
  ansible.builtin.file:
    group: label_studio_admin
    mode: '0770'
    owner: root
    path: /share/label-studio/files
    state: directory
