- name: Deploy label_studio password
  ansible.builtin.script:
    cmd: scripts/deploy_label_studio_pass.sh
    creates: "{{ansible_env.HOME}}/waiter/.secrets/label_studio_admin_password.env"
    executable: /bin/bash
    chdir: "{{ansible_env.HOME}}/waiter"
- name: Ensure label studio admin group exists
  become: true
  ansible.builtin.group:
    name: label_studio_admin

- name: Ensure label studio files dir exists
  become: true
  ansible.builtin.file:
    group: label_studio_admin
    mode: '0770'
    owner: root
    path: /share/label-studio/files
    state: directory

- name: Ensure label studio data dir exists
  become: true
  ansible.builtin.file:
    group: root
    owner: waiter-admin
    path: "{{ansible_env.HOME}}/waiter/label_studio_data"
    state: directory
    mode: '0770'
