- name: Download nix package manager
  ansible.builtin.get_url:
    url: https://nixos.org/nix/install
    checksum: sha256:81722b9b3f5f5e08e6fcbae775196c68b7d7787d15b9bd16e2e22ed085555453
    dest: '{{ansible_env.HOME}}/installers/nix-install.sh'

- name: Install nix package manager
  become: true
  ansible.builtin.script:
    cmd: '{{ansible_env.HOME}}/installers/nix-install.sh --yes --daemon'
    creates: /nix/var/nix/profiles/default/bin/nix
    executable: /bin/bash
    chdir: "{{ansible_env.HOME}}/installers"

- name: Add nixpkgs unstable channel
  ansible.builtin.command: nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs
  register: nixpkgs_channel
  changed_when: "'https://nixos.org/channels/nixpkgs-unstable' not in nixpkgs_channel.stdout"

- name: Add home-manager master channel
  ansible.builtin.command: nix-channel --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager
  register: hm_channel
  changed_when: "'master.tar.gz' not in hm_channel.stdout"
  
- name: Update Nix channels
  ansible.builtin.command: nix-channel --update
  when: nixpkgs_channel.changed or hm_channel.changed