- name: KRG Waiter
  hosts: localhost
  remote_user: root
  tasks:
  - name: Set timezone to America/Los_Angeles
    become: true
    community.general.timezone:
      name: America/Los_Angeles
  - name: Ensure that system is up to date
    become: true
    apt:
      name: "*"
      state: latest
      update_cache: yes
  - name: Install/update system packages
    become: true
    apt:
      pkg:
        - ca-certificates
        - curl
  - import_tasks: docker_ubuntu_24.yaml
  - import_tasks: cuda_12_6_1_ubuntu_24.yaml
