- name: KRG Waiter
  hosts: localhost
  remote_user: root
  tasks:
  - name: Set timezone to America/Los_Angeles
    community.general.timezone:
      name: America/Los_Angeles
  - name: Stop and disable NetworkManager
    become: true
    ansible.builtin.systemd_service:
      state: stopped
      name: NetworkManager
      enabled: false
  - name: Start and enable networkd
    become: true
    ansible.builtin.systemd_service:
      state: started
      name: systemd-networkd
      enabled: true
  - name: Start and enable resolved
    become: true
    ansible.builtin.systemd_service:
      state: started
      enabled: true
      name: sytemd-resolvd
  - name: Set resolve.conf
    become: true
    ansible.builtin.shell: |
      rm /etc/resolv.conf
      ln -s /run/systemd/resolve/resolv.conf /etc/resolv.conf

  - name: Ensure that system is up to date
    apt:
      name: "*"
      state: latest
      update_cache: yes
  - name: Install/update system packages
    apt:
      pkg:
        - ca-certificates
        - curl
  # - name: Enable node-exporter
    # prometheus.prometheus.node_exporter:
      # node_exporter_version: "1.8.2"

  - import_tasks: docker_ubuntu_24.yaml
