- name: Install/update dependency packages
  become: true
  ansible.builtin.apt:
    pkg:
      - libstdc++6
      - libgtk2.0-0
      - dpkg-dev
      - python3-pip
      - libxtst6
      - libtinfo5
      - libncurses5
      # - libx11
      - libxext6
      - libxrender1
      - libsm6
      # - libqtgui4
      - libfontconfig1
      - unzip
      - zip
      - g++
      - xvfb
      - git
      # - libncursesw5
      - libc6-dev-i386
      - net-tools
      - graphviz
      - make
      - libexpat1-dev
      - libapr1
      - libapr1-dev
      - libaprutil1
- name: Configure Xilinx License server
  become: true
  ansible.builtin.lineinfile:
    path: /etc/environment
    regexp: 'XILINXD_LICENSE_FILE\=\"2100@cselm2.ucsd.edu\"'
    line: 'XILINXD_LICENSE_FILE="2100@cselm2.ucsd.edu"'
    owner: root
    group: root
    mode: '0644'

# Xilinx 2018.2
- name: Unzip Vivado 2018.2
  tags: [test]
  ansible.builtin.unarchive:
    src: "{{ansible_env.HOME}}/installers/Xilinx/Xilinx_Vivado_SDK_2018.2_0614_1954.tar.gz"
    dest: /tmp
    remote_src: yes
    creates: /tmp/Xilinx_Vivado_SDK_2018.2_0614_1954/xsetup
- name: Deploy 2018.2 Installer Config
  tags: [test]
  ansible.builtin.copy:
    src: xic_config/vivado_2018.2.txt
    dest: "{{ansible_env.HOME}}/installers/Xilinx/vivado_2018.2.txt"
- name: Install Vivado 2018.2
  tags: [test]
  ansible.builtin.command:
    cmd: /tmp/Xilinx_Vivado_SDK_2018.2_0614_1954/xsetup -b Install -a 3rdPartyEULA,WebTalkTerms,XilinxEULA -c "{{ansible_env.HOME}}/installers/Xilinx/vivado_2018.2.txt"
    creates: /tools/Xilinx/Vivado/2018.2/bin/vivado


# Xilinx 2019.1
- name: Unzip Vivado 2019.1
  tags: [test]
  ansible.builtin.unarchive:
    src: "{{ansible_env.HOME}}/installers/Xilinx/Xilinx_Vivado_SDK_2019.1_0524_1430.tar.gz"
    dest: /tmp
    remote_src: yes
    creates: /tmp/Xilinx_Vivado_SDK_2019.1_0524_1430/xsetup
- name: Deploy 2019.1 Installer Config
  tags: [test]
  ansible.builtin.copy:
    src: xic_config/vivado_2019.1.txt
    dest: "{{ansible_env.HOME}}/installers/Xilinx/vivado_2019.1.txt"
- name: Install Vivado 2019.1
  tags: [test]
  ansible.builtin.command:
    cmd: /tmp/Xilinx_Vivado_SDK_2019.1_0524_1430/xsetup -b Install --agree XilinxEULA,3rdPartyEULA,WebTalkTerms -c "{{ansible_env.HOME}}/installers/Xilinx/vivado_2019.1.txt"
    creates: /tools/Xilinx/Vivado/2019.1/bin/vivado

# Xilinx 2020.2
- name: Unzip Vivado 2020.2
  tags: [test]
  ansible.builtin.unarchive:
    src: "{{ansible_env.HOME}}/installers/Xilinx/Xilinx_Unified_2020.2_1118_1232.tar.gz"
    dest: /tmp
    remote_src: yes
    creates: /tmp/Xilinx_Unified_2020.2_1118_1232/xsetup
- name: Deploy 2020.2 Installer Config
  tags: [test]
  ansible.builtin.copy:
    src: xic_config/vivado_2020.2.txt
    dest: "{{ansible_env.HOME}}/installers/Xilinx/vivado_2020.2.txt"
- name: Install Vivado 2020.2
  tags: [test]
  ansible.builtin.command:
    cmd: /tmp/Xilinx_Unified_2020.2_1118_1232/xsetup -b Install --agree XilinxEULA,3rdPartyEULA,WebTalkTerms -c "{{ansible_env.HOME}}/installers/Xilinx/vivado_2020.2.txt"
    creates: /tools/Xilinx/Vivado/2020.2/bin/vivado

# Xilinx 2022.2
- name: Unzip Vivado 2022.2
  tags: [test]
  ansible.builtin.unarchive:
    src: "{{ansible_env.HOME}}/installers/Xilinx/Xilinx_Unified_2022.2_1014_8888.tar.gz"
    dest: /tmp
    remote_src: yes
    creates: /tmp/Xilinx_Unified_2022.2_1014_8888/xsetup
- name: Deploy 2022.2 Installer Config
  tags: [test]
  ansible.builtin.copy:
    src: xic_config/vivado_2022.2.txt
    dest: "{{ansible_env.HOME}}/installers/Xilinx/vivado_2022.2.txt"
- name: Install Vivado 2022.2
  tags: [test]
  ansible.builtin.command:
    cmd: /tmp/Xilinx_Unified_2022.2_1014_8888/xsetup -b Install --agree XilinxEULA,3rdPartyEULA,WebTalkTerms -c "{{ansible_env.HOME}}/installers/Xilinx/vivado_2022.2.txt"
    creates: /tools/Xilinx/Vivado/2022.2/bin/vivado

# Xilinx 2024.1
- name: Unzip Vivado 2024.1
  tags: [test]
  ansible.builtin.unarchive:
    src: "{{ansible_env.HOME}}/installers/Xilinx/FPGAs_AdaptiveSoCs_Unified_2024.1_0522_2023.tar"
    dest: /tmp
    remote_src: yes
    creates: /tmp/FPGAs_AdaptiveSoCs_Unified_2024.1_0522_2023/xsetup
- name: Deploy 2024.1 Installer Config
  tags: [test]
  ansible.builtin.copy:
    src: xic_config/vivado_2024.1.txt
    dest: "{{ansible_env.HOME}}/installers/Xilinx/vivado_2024.1.txt"
- name: Install Vivado 2024.1
  tags: [test]
  ansible.builtin.command:
    cmd: /tmp/FPGAs_AdaptiveSoCs_Unified_2024.1_0522_2023/xsetup -b Install --agree XilinxEULA,3rdPartyEULA,WebTalkTerms -c "{{ansible_env.HOME}}/installers/Xilinx/vivado_2024.1.txt"
    creates: /tools/Xilinx/Vivado/2024.1/bin/vivado
