- name: Install/update dependency packages
  become: true
  ansible.builtin.apt:
    pkg:
      - libstdc++6
      - libgtk2.0-0
      - dpkg-dev
      - python3-pip
      - libxtst6
      - libtinfo5
      - libncurses5
      # - libx11
      - libxext6
      - libxrender1
      - libsm6
      # - libqtgui4
      - libfontconfig1
      - unzip
      - zip
      - g++
      - xvfb
      - git
      # - libncursesw5
      - libc6-dev-i386
      - net-tools
      - graphviz
      - make
      - libexpat1-dev
      - libapr1
      - libapr1-dev
      - libaprutil1
- name: Configure Xilinx License server
  become: true
  ansible.builtin.lineinfile:
    path: /etc/environment
    regexp: 'XILINXD_LICENSE_FILE\=\"2100@cselm2.ucsd.edu\"'
    line: 'XILINXD_LICENSE_FILE="2100@cselm2.ucsd.edu"'
    owner: root
    group: root
    mode: '0644'

# Xilinx 2018.2.2
- name: Ensure Xilinx 2018.2.2 installer dir exists
  ansible.builtin.file:
    path: /tmp/Xilinx_Vivado_SDx_Update/2018.2.2_1001_1805
    state: directory
- name: Unzip Vivado
  ansible.builtin.unarchive:
    src: "{{ansible_env.HOME}}/installers/Xilinx/Xilinx_Vivado_SDx_Update/2018.2.2_1001_1805.tar.gz"
    dest: /tmp/Xilinx_Vivado_SDx_Update/2018.2.2_1001_1805
    remote_src: yes