- name: Install/update dependency packages
  become: true
  ansible.builtin.apt:
    pkg:
      - libstdc++6
      - libgtk2.0-0
      - dpkg-dev
      - python3-pip
      - libxtst6
      - libtinfo5
      - libncurses5
      - libx11
      - libxext6
      - libxrender1
      - libsm6
      - libqtgui4
      - libfontconfig1
      - unzip
      - zip
      - g++
      - xvfb
      - git
      - libncursesw5
      - libc6-dev-i386
      - net-tools
      - graphviz
      - make
      - libexpat1-dev
      - libapr1
      - libapr1-dev
      - libaprutil1
- name: Configure Xilinx License server
  become: true
  ansible.builtin.lineinfile:
    path: /etc/environment
    regexp: 'XILINXD_LICENSE_FILE\=\"2100@cselm2.ucsd.edu\"'
    line: 'XILINXD_LICENSE_FILE="2100@cselm2.ucsd.edu"'
    owner: root
    group: root
    mode: '0644'
