global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'codelab-monitor'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'node_exporter'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
      - targets:
          - waiter.ucsd.edu:9100
          - kastner-ml.ucsd.edu:9100
          - fabricant.ucsd.edu:9100

    # tls_config:
    #   # CA certificate to validate API server certificate with. At most one of ca and ca_file is allowed.
    #   # [ ca: <string> ]
    #   ca_file: /certs/e4e_ucsd_ca.crt

    #   # Certificate and key for client cert authentication to the server.
    #   # At most one of cert and cert_file is allowed.
    #   # At most one of key and key_file is allowed.
    #   cert_file: /certs/e4e-gateway.ucsd.edu.crt
    #   key_file: /certs/e4e-gateway.ucsd.edu.key
  - job_name: 'dcgm_exporter'
    scrape_interval: 15s
    static_configs:
      - targets:
        - dcgm_exporter:9400
        - kastner-ml.ucsd.edu:9400
  - job_name: 'docker_exporter'
    scrape_interval: 15s
    static_configs:
      - targets:
        - waiter.ucsd.edu:9323
        - kastner-ml.ucsd.edu:9323
  - job_name: ansible_deploy_monitor
    scrape_interval: 5s
    static_configs:
      - targets:
        - waiter.ucsd.edu:9000
        - kastner-ml.ucsd.edu:9000
        - fabricant.ucsd.edu:9000
  - job_name: ipmi_exporter
    scrape_interval: 15s
    static_configs:
      - targets:
        - localhost:9290
        - fabricant.ucsd.edu:9290