global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'codelab-monitor'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'label_studio_slack_reporter'
    scrape_interval: 30s
    static_configs:
      - targets:
          - fabricant.ucsd.edu:9101

  - job_name: 'node_exporter'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
      - targets:
          - waiter.ucsd.edu:9100
          - kastner-ml.ucsd.edu:9100
          - fabricant.ucsd.edu:9100
          - e4e-fishsense-mobile-endpoint.dynamic.ucsd.edu:9100

    # tls_config:
    #   # CA certificate to validate API server certificate with. At most one of ca and ca_file is allowed.
    #   # [ ca: <string> ]
    #   ca_file: /certs/e4e_ucsd_ca.crt

    #   # Certificate and key for client cert authentication to the server.
    #   # At most one of cert and cert_file is allowed.
    #   # At most one of key and key_file is allowed.
    #   cert_file: /certs/e4e-gateway.ucsd.edu.crt
    #   key_file: /certs/e4e-gateway.ucsd.edu.key
  - job_name: 'dcgm_exporter'
    scrape_interval: 15s
    static_configs:
      - targets:
        - dcgm_exporter:9400
        - kastner-ml.ucsd.edu:9400
  - job_name: 'docker_exporter'
    scrape_interval: 15s
    static_configs:
      - targets:
        - waiter.ucsd.edu:9323
        - kastner-ml.ucsd.edu:9323
        - e4e-fishsense-mobile-endpoint.dynamic.ucsd.edu:9323
  - job_name: ansible_deploy_monitor
    scrape_interval: 5s
    static_configs:
      - targets:
        - waiter.ucsd.edu:9000
        - kastner-ml.ucsd.edu:9000
        - fabricant.ucsd.edu:9000
        - e4e-fishsense-mobile-endpoint.dynamic.ucsd.edu:9000
  - job_name: ipmi_exporter
    scrape_interval: 15s
    static_configs:
      - targets:
        - localhost:9290
        - fabricant.ucsd.edu:9290
  - job_name: 'blackbox_exporter'  # collect blackbox exporter's operational metrics.
    static_configs:
      - targets:
        - blackbox_exporter:9115

  - job_name: website_monitoring
    scrape_interval: 1m
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://e4e.ucsd.edu/
        - https://kastner.ucsd.edu/
        - https://e4e-nas.ucsd.edu:6021/
        - https://e4e-octopi.dynamic.ucsd.edu/login/
        - https://labeler.e4e.ucsd.edu/version
        - https://dashboard.waiter.ucsd.edu/login
        - https://vault.e4e-gateway.ucsd.edu/
        - https://etap.nsf.gov/award/2378/opportunity/10235
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115  # The blackbox exporter's real hostname:port.

  - job_name: blackbox-ping
    scrape_interval: 1m
    metrics_path: /probe
    params:
      module: [icmp]
    static_configs:
      - targets:
        - '1.1.1.1' # one.one.one.one
        - '8.8.8.8' # dns.google
        - waiter.ucsd.edu
        - kastner-ml.ucsd.edu
        - fabricant.ucsd.edu
        - e4e-octopi.dynamic.ucsd.edu
        - e4e-gateway.ucsd.edu
        - e4e-fishsense-mobile-endpoint.dynamic.ucsd.edu
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115  # The blackbox exporter's real hostname:port.    
