- name: Deploy gf_admin_password
  ansible.builtin.shell:
    cmd: '{{ansible_env.HOME}}/.nvm/versions/node/v22.9.0/bin/node {{ansible_env.HOME}}/.nvm/versions/node/v22.9.0/lib/node_modules/@bitwarden/cli/build/bw.js --session `cat .bw_session` get password dashboard.waiter.ucsd.edu admin > {{ansible_env.HOME}}/waiter/.secrets/gf_admin_password.txt'
    chdir: '{{ansible_env.HOME}}/waiter'
    creates: '{{ansible_env.HOME}}/waiter/.secrets/gf_admin_password.txt'

# Postgres
- name: Deploy pg admin password
  ansible.builtin.shell:
    cmd: '{{ansible_env.HOME}}/.nvm/versions/node/v22.9.0/bin/node {{ansible_env.HOME}}/.nvm/versions/node/v22.9.0/lib/node_modules/@bitwarden/cli/build/bw.js --session `cat .bw_session` get password "Waiter Postgres Admin" > {{ansible_env.HOME}}/waiter/.secrets/postgres_admin_password.txt'
    chdir: '{{ansible_env.HOME}}/waiter'
    creates: '{{ansible_env.HOME}}/waiter/.secrets/postgres_admin_password.txt'
- name: Deploy pg data dir
  ansible.builtin.file:
    mode: '0700'
    group: 1000
    owner: 1000
    path: '{{ansible_env.HOME}}/waiter/postgres/data'
    state: directory

# Segment Anything
- name: Deploy SAM env
  ansible.builtin.script:
    cmd: scripts/deploy_sam_pass.sh
    creates: "{{ansible_env.HOME}}/waiter/.secrets/segment_anything.env"
    executable: /bin/bash
    chdir: "{{ansible_env.HOME}}/waiter"